// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory_pipeline.sql

package sqlc

import (
	"context"
)

const deleteMemoryPipelineState = `-- name: DeleteMemoryPipelineState :exec
DELETE FROM memory_pipeline_state
WHERE bot_id = $1
`

func (q *Queries) DeleteMemoryPipelineState(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, deleteMemoryPipelineState, botID)
	return err
}

const getMemoryPipelineState = `-- name: GetMemoryPipelineState :one
SELECT bot_id, buffer_json, threshold, warmup_index, retry_count, updated_at
FROM memory_pipeline_state
WHERE bot_id = $1
`

func (q *Queries) GetMemoryPipelineState(ctx context.Context, botID string) (MemoryPipelineState, error) {
	row := q.db.QueryRow(ctx, getMemoryPipelineState, botID)
	var i MemoryPipelineState
	err := row.Scan(
		&i.BotID,
		&i.BufferJson,
		&i.Threshold,
		&i.WarmupIndex,
		&i.RetryCount,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemoryPipelineStates = `-- name: ListMemoryPipelineStates :many
SELECT bot_id, buffer_json, threshold, warmup_index, retry_count, updated_at
FROM memory_pipeline_state
ORDER BY updated_at DESC
`

func (q *Queries) ListMemoryPipelineStates(ctx context.Context) ([]MemoryPipelineState, error) {
	rows, err := q.db.Query(ctx, listMemoryPipelineStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryPipelineState
	for rows.Next() {
		var i MemoryPipelineState
		if err := rows.Scan(
			&i.BotID,
			&i.BufferJson,
			&i.Threshold,
			&i.WarmupIndex,
			&i.RetryCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemoryPipelineState = `-- name: UpsertMemoryPipelineState :exec
INSERT INTO memory_pipeline_state (bot_id, buffer_json, threshold, warmup_index, retry_count, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (bot_id) DO UPDATE SET
    buffer_json = EXCLUDED.buffer_json,
    threshold = EXCLUDED.threshold,
    warmup_index = EXCLUDED.warmup_index,
    retry_count = EXCLUDED.retry_count,
    updated_at = NOW()
`

type UpsertMemoryPipelineStateParams struct {
	BotID       string `json:"bot_id"`
	BufferJson  []byte `json:"buffer_json"`
	Threshold   int32  `json:"threshold"`
	WarmupIndex int32  `json:"warmup_index"`
	RetryCount  int32  `json:"retry_count"`
}

func (q *Queries) UpsertMemoryPipelineState(ctx context.Context, arg UpsertMemoryPipelineStateParams) error {
	_, err := q.db.Exec(ctx, upsertMemoryPipelineState,
		arg.BotID,
		arg.BufferJson,
		arg.Threshold,
		arg.WarmupIndex,
		arg.RetryCount,
	)
	return err
}
