// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipeline = `-- name: CreatePipeline :one

INSERT INTO pipelines (bot_id, goal, status)
VALUES ($1, $2, $3)
RETURNING id, bot_id, goal, status, created_at, updated_at
`

type CreatePipelineParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	Goal   string      `json:"goal"`
	Status string      `json:"status"`
}

// Pipeline CRUD
func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline, arg.BotID, arg.Goal, arg.Status)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Goal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipelineNode = `-- name: CreatePipelineNode :one

INSERT INTO pipeline_nodes (
    pipeline_id, name, description, depends_on, model_tier,
    status, input, max_retries, timeout_seconds, needs_review
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
`

type CreatePipelineNodeParams struct {
	PipelineID     pgtype.UUID   `json:"pipeline_id"`
	Name           string        `json:"name"`
	Description    pgtype.Text   `json:"description"`
	DependsOn      []pgtype.UUID `json:"depends_on"`
	ModelTier      string        `json:"model_tier"`
	Status         string        `json:"status"`
	Input          []byte        `json:"input"`
	MaxRetries     int32         `json:"max_retries"`
	TimeoutSeconds int32         `json:"timeout_seconds"`
	NeedsReview    bool          `json:"needs_review"`
}

// Pipeline Node CRUD
func (q *Queries) CreatePipelineNode(ctx context.Context, arg CreatePipelineNodeParams) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, createPipelineNode,
		arg.PipelineID,
		arg.Name,
		arg.Description,
		arg.DependsOn,
		arg.ModelTier,
		arg.Status,
		arg.Input,
		arg.MaxRetries,
		arg.TimeoutSeconds,
		arg.NeedsReview,
	)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteNodesByPipeline = `-- name: DeleteNodesByPipeline :exec
DELETE FROM pipeline_nodes
WHERE pipeline_id = $1
`

func (q *Queries) DeleteNodesByPipeline(ctx context.Context, pipelineID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNodesByPipeline, pipelineID)
	return err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines
WHERE id = $1
`

func (q *Queries) DeletePipeline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePipeline, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
FROM pipeline_nodes
WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, bot_id, goal, status, created_at, updated_at
FROM pipelines
WHERE id = $1
`

func (q *Queries) GetPipeline(ctx context.Context, id pgtype.UUID) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipeline, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Goal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementNodeRetry = `-- name: IncrementNodeRetry :one
UPDATE pipeline_nodes
SET retry_count = retry_count + 1, status = 'pending', updated_at = now()
WHERE id = $1
RETURNING id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
`

func (q *Queries) IncrementNodeRetry(ctx context.Context, id pgtype.UUID) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, incrementNodeRetry, id)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listNodesByPipeline = `-- name: ListNodesByPipeline :many
SELECT id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
FROM pipeline_nodes
WHERE pipeline_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListNodesByPipeline(ctx context.Context, pipelineID pgtype.UUID) ([]PipelineNode, error) {
	rows, err := q.db.Query(ctx, listNodesByPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineNode
	for rows.Next() {
		var i PipelineNode
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Description,
			&i.DependsOn,
			&i.ModelTier,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.Error,
			&i.RetryCount,
			&i.MaxRetries,
			&i.TimeoutSeconds,
			&i.NeedsReview,
			&i.ReviewResult,
			&i.ReviewFeedback,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByBot = `-- name: ListPipelinesByBot :many
SELECT id, bot_id, goal, status, created_at, updated_at
FROM pipelines
WHERE bot_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPipelinesByBotParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListPipelinesByBot(ctx context.Context, arg ListPipelinesByBotParams) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByBot, arg.BotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Goal,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeError = `-- name: UpdateNodeError :one
UPDATE pipeline_nodes
SET error = $2, status = 'failed', completed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
`

type UpdateNodeErrorParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) UpdateNodeError(ctx context.Context, arg UpdateNodeErrorParams) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, updateNodeError, arg.ID, arg.Error)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateNodeOutput = `-- name: UpdateNodeOutput :one
UPDATE pipeline_nodes
SET output = $2, status = $3,
    completed_at = CASE WHEN $3 IN ('completed', 'failed') THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
`

type UpdateNodeOutputParams struct {
	ID     pgtype.UUID `json:"id"`
	Output []byte      `json:"output"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateNodeOutput(ctx context.Context, arg UpdateNodeOutputParams) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, updateNodeOutput, arg.ID, arg.Output, arg.Status)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateNodeReview = `-- name: UpdateNodeReview :one
UPDATE pipeline_nodes
SET review_result = $2, review_feedback = $3, updated_at = now()
WHERE id = $1
RETURNING id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
`

type UpdateNodeReviewParams struct {
	ID             pgtype.UUID `json:"id"`
	ReviewResult   pgtype.Text `json:"review_result"`
	ReviewFeedback pgtype.Text `json:"review_feedback"`
}

func (q *Queries) UpdateNodeReview(ctx context.Context, arg UpdateNodeReviewParams) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, updateNodeReview, arg.ID, arg.ReviewResult, arg.ReviewFeedback)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :one
UPDATE pipeline_nodes
SET status = $2,
    started_at = CASE WHEN $2 = 'running' THEN COALESCE(started_at, now()) ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, pipeline_id, name, description, depends_on, model_tier,
    status, input, output, error, retry_count, max_retries,
    timeout_seconds, needs_review, review_result, review_feedback,
    created_at, updated_at, started_at, completed_at
`

type UpdateNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) (PipelineNode, error) {
	row := q.db.QueryRow(ctx, updateNodeStatus, arg.ID, arg.Status)
	var i PipelineNode
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.ModelTier,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutSeconds,
		&i.NeedsReview,
		&i.ReviewResult,
		&i.ReviewFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePipelineStatus = `-- name: UpdatePipelineStatus :one
UPDATE pipelines
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, bot_id, goal, status, created_at, updated_at
`

type UpdatePipelineStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePipelineStatus(ctx context.Context, arg UpdatePipelineStatusParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, updatePipelineStatus, arg.ID, arg.Status)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Goal,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
